#!/usr/bin/env escript

% The MIT License (MIT)

% Copyright (c) 2015 Christopher Lillthors

% Permission is hereby granted, free of charge, to any person obtaining a copy
% of this software and associated documentation files (the "Software"), to deal
% in the Software without restriction, including without limitation the rights
% to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
% copies of the Software, and to permit persons to whom the Software is
% furnished to do so, subject to the following conditions:

% The above copyright notice and this permission notice shall be included in
% all copies or substantial portions of the Software.

% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
% IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
% FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
% AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
% LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
% OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
% THE SOFTWARE.

main([N]) ->
	try
		M = list_to_integer(N),
		if
			M >= 0 ->
				io:format("Running bernoulliconcurrent(~p)~n",[M]),
				progp:bernoulliconcurrent(M);
			true ->
				io:format("Number >= 0~n"),
				halt(1)
		end
	catch
		%gotta catch them all
		_:_ ->
			usage()
	end;

main(_) ->
	usage().

usage() ->
	io:format("Please specify the number of bernoulli numbers you want~n"),
	halt(1).